### ISSUE TITLE
Support for Python3?

### ISSUE THREAD

**Issue by InfernoZeus** [joaquincasares/python-wifi-leds#2]
I've been trying to update this to support Python3. The main thing was changing print calls to use brackets, but now I'm getting the following error:

`
Traceback (most recent call last):
  File "NG-led.py", line 1, in <module>
    import limitlessled
  File "..../limitlessled/__init__.py", line 2, in <module>
    from . import effects
  File "..../limitlessled/effects/__init__.py", line 5, in <module>
    __import__(module[:-3], locals(), globals())
ImportError: No module named 'colorful_strobe'
`

Any idea what the problem is? What's the code in `effects/**init**.py' doing?

**Comment by joaquincasares** [comment]
Sorry for sleeping on this! I saw this come in, but somehow a month's past. Did you get it to work after all?

effects/**init**.py is essentially loading all the files that are under that directory. I did that to make it simple to add new effects. If you were instead to hardcode all the effects into init.py, would that make Python3 happy?

Again, apologies for being late here. Cheers!
